version: "2"
services:
    node:
        build: .
        user: node
        working_dir: /home/node/src
        volumes:
            - .:/home/node/src
        ports:
            - "9999:9999"
        command: './run.sh'
