version: "2"
services:
    web:
        build: .
        user: app
        working_dir: /home/app/src
        ports:
            - "8888:8888"
        volumes:
            - .:/home/app/src
        command: './run.sh'
