parameters:
    paysera_challenge.challenges:
        -
            identifier: addition
            description: |
                Create a function which could return the sum of two numbers.
            test_cases:
                - { arguments: [15, 17] result: 32 }
                - { arguments: [-87, 87] result: 0 }
                - { arguments: [0.00001, 0.00002] result: 0.00003 }

        -
            identifier: fibonacci
            description: |
                Create a function which could return the n-th fibonacci number with respect to first and second term:
                fibonacci(first, second, nth)
                i.e. fibonacci(1, 1, 6) => 8 - sixth number in fibonacci sequence starting from 1 and 1 is 8
            test_cases:
                - { arguments: [1, 1, 6] result: 8 }
                - { arguments: [0, 1, 7] result: 8 }
                - { arguments: [5, 8, 4] result: 21 }

        -
            identifier: reverse
            description: |
                Create a function which could return string in reversed order, i.e.: CAT => TAC, DOG => GOD
            test_cases:
                - { arguments: ['cat'] result: 'tac' }
                - { arguments: ['hello world!'] result: '!dlrow olleh' }

        -
            identifier: count-sheep
            description: |
                Create a function which could count how many appearances of given character is in string, i.e:
                string: "hello world", char: "o" => appearances: 2
            test_cases:
                - { arguments: ['dfdf1sdf11', '11'] result: 1 }
                - { arguments: ['hello world!', 'l'] result: 3 }
                - { arguments: ['Quick quick', 'q'] result: 1 }

        -
            identifier: addition-advanced
            description: |
                For the given number, return the sum of it's individual digits, i.e.: 1566 => 18; 11 => 2; 20 => 2
            test_cases:
                - { arguments: [101] result: 2 }
                - { arguments: [90] result: 9 }
                - { arguments: [123] result: 6 }
